# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.cache/wt [current_project]
set_property parent.project_path /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/jf2715/BNN-PYNQ/bnn/src/network/output/hls-syn/lfcW1A1-pynqZ1-Z2/sol1/impl/ip [current_project]
set_property ip_output_repo /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/hdl/procsys_wrapper.v
add_files /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/procsys.bd
set_property used_in_implementation false [get_files -all /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_ps7_0/procsys_ps7_0.xdc]
set_property used_in_implementation false [get_files -all /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/constraints/BlackBoxJam_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_rst_ps7_100M_0/procsys_rst_ps7_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_rst_ps7_100M_0/procsys_rst_ps7_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_rst_ps7_100M_0/procsys_rst_ps7_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_auto_pc_0/procsys_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_auto_pc_1/procsys_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/procsys_ooc.xdc]
set_property is_locked true [get_files /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/procsys.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jf2715/BNN-PYNQ/bnn/src/library/script/pynqZ1-Z2/pynqZ1-Z2.xdc
set_property used_in_implementation false [get_files /home/jf2715/BNN-PYNQ/bnn/src/library/script/pynqZ1-Z2/pynqZ1-Z2.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top procsys_wrapper -part xc7z020clg400-1 -fanout_limit 400 -directive AlternateRoutability -retiming -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef procsys_wrapper.dcp

catch { report_utilization -file procsys_wrapper_utilization_synth.rpt -pb procsys_wrapper_utilization_synth.pb }
