// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "Mem2Stream_Batch12.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Mem2Stream_Batch12::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic Mem2Stream_Batch12::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> Mem2Stream_Batch12::ap_ST_fsm_state1 = "1";
const sc_lv<9> Mem2Stream_Batch12::ap_ST_fsm_state2 = "10";
const sc_lv<9> Mem2Stream_Batch12::ap_ST_fsm_state3 = "100";
const sc_lv<9> Mem2Stream_Batch12::ap_ST_fsm_state4 = "1000";
const sc_lv<9> Mem2Stream_Batch12::ap_ST_fsm_state5 = "10000";
const sc_lv<9> Mem2Stream_Batch12::ap_ST_fsm_state6 = "100000";
const sc_lv<9> Mem2Stream_Batch12::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> Mem2Stream_Batch12::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> Mem2Stream_Batch12::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> Mem2Stream_Batch12::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> Mem2Stream_Batch12::ap_const_lv1_1 = "1";
const bool Mem2Stream_Batch12::ap_const_boolean_1 = true;
const sc_lv<64> Mem2Stream_Batch12::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<1> Mem2Stream_Batch12::ap_const_lv1_0 = "0";
const sc_lv<3> Mem2Stream_Batch12::ap_const_lv3_0 = "000";
const sc_lv<2> Mem2Stream_Batch12::ap_const_lv2_0 = "00";
const sc_lv<4> Mem2Stream_Batch12::ap_const_lv4_0 = "0000";
const sc_lv<8> Mem2Stream_Batch12::ap_const_lv8_0 = "00000000";
const sc_lv<32> Mem2Stream_Batch12::ap_const_lv32_1 = "1";
const sc_lv<32> Mem2Stream_Batch12::ap_const_lv32_5 = "101";
const sc_lv<32> Mem2Stream_Batch12::ap_const_lv32_8 = "1000";
const sc_lv<32> Mem2Stream_Batch12::ap_const_lv32_7 = "111";
const sc_lv<32> Mem2Stream_Batch12::ap_const_lv32_6 = "110";
const sc_lv<32> Mem2Stream_Batch12::ap_const_lv32_D = "1101";
const sc_lv<32> Mem2Stream_Batch12::ap_const_lv32_10 = "10000";

Mem2Stream_Batch12::Mem2Stream_Batch12(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_Mem2Stream_1_fu_92 = new Mem2Stream_1("grp_Mem2Stream_1_fu_92");
    grp_Mem2Stream_1_fu_92->ap_clk(ap_clk);
    grp_Mem2Stream_1_fu_92->ap_rst(ap_rst);
    grp_Mem2Stream_1_fu_92->ap_start(grp_Mem2Stream_1_fu_92_ap_start);
    grp_Mem2Stream_1_fu_92->ap_done(grp_Mem2Stream_1_fu_92_ap_done);
    grp_Mem2Stream_1_fu_92->ap_idle(grp_Mem2Stream_1_fu_92_ap_idle);
    grp_Mem2Stream_1_fu_92->ap_ready(grp_Mem2Stream_1_fu_92_ap_ready);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWVALID(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWVALID);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWREADY(ap_var_for_const0);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWADDR(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWADDR);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWID(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWID);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWLEN(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWLEN);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWSIZE(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWSIZE);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWBURST(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWBURST);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWLOCK(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWLOCK);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWCACHE(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWCACHE);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWPROT(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWPROT);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWQOS(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWQOS);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWREGION(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWREGION);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_AWUSER(grp_Mem2Stream_1_fu_92_m_axi_in_V_AWUSER);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_WVALID(grp_Mem2Stream_1_fu_92_m_axi_in_V_WVALID);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_WREADY(ap_var_for_const0);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_WDATA(grp_Mem2Stream_1_fu_92_m_axi_in_V_WDATA);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_WSTRB(grp_Mem2Stream_1_fu_92_m_axi_in_V_WSTRB);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_WLAST(grp_Mem2Stream_1_fu_92_m_axi_in_V_WLAST);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_WID(grp_Mem2Stream_1_fu_92_m_axi_in_V_WID);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_WUSER(grp_Mem2Stream_1_fu_92_m_axi_in_V_WUSER);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARVALID(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARVALID);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARREADY(m_axi_in_V_ARREADY);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARADDR(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARADDR);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARID(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARID);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARLEN(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLEN);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARSIZE(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARSIZE);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARBURST(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARBURST);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARLOCK(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLOCK);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARCACHE(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARCACHE);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARPROT(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARPROT);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARQOS(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARQOS);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARREGION(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARREGION);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_ARUSER(grp_Mem2Stream_1_fu_92_m_axi_in_V_ARUSER);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_RVALID(m_axi_in_V_RVALID);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_RREADY(grp_Mem2Stream_1_fu_92_m_axi_in_V_RREADY);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_RDATA(m_axi_in_V_RDATA);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_RLAST(m_axi_in_V_RLAST);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_RID(m_axi_in_V_RID);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_RUSER(m_axi_in_V_RUSER);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_RRESP(m_axi_in_V_RRESP);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_BVALID(ap_var_for_const0);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_BREADY(grp_Mem2Stream_1_fu_92_m_axi_in_V_BREADY);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_BRESP(ap_var_for_const1);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_BID(ap_var_for_const2);
    grp_Mem2Stream_1_fu_92->m_axi_in_V_BUSER(ap_var_for_const2);
    grp_Mem2Stream_1_fu_92->in_V1(in_V1);
    grp_Mem2Stream_1_fu_92->tmp_6(tmp_5_i_i_i_i_reg_200);
    grp_Mem2Stream_1_fu_92->out_V_V_din(grp_Mem2Stream_1_fu_92_out_V_V_din);
    grp_Mem2Stream_1_fu_92->out_V_V_full_n(memInStrm_V_V_full_n);
    grp_Mem2Stream_1_fu_92->out_V_V_write(grp_Mem2Stream_1_fu_92_out_V_V_write);
    grp_Mem2Stream_fu_102 = new Mem2Stream("grp_Mem2Stream_fu_102");
    grp_Mem2Stream_fu_102->ap_clk(ap_clk);
    grp_Mem2Stream_fu_102->ap_rst(ap_rst);
    grp_Mem2Stream_fu_102->ap_start(grp_Mem2Stream_fu_102_ap_start);
    grp_Mem2Stream_fu_102->ap_done(grp_Mem2Stream_fu_102_ap_done);
    grp_Mem2Stream_fu_102->ap_idle(grp_Mem2Stream_fu_102_ap_idle);
    grp_Mem2Stream_fu_102->ap_ready(grp_Mem2Stream_fu_102_ap_ready);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWVALID(grp_Mem2Stream_fu_102_m_axi_in_V_AWVALID);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWREADY(ap_var_for_const0);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWADDR(grp_Mem2Stream_fu_102_m_axi_in_V_AWADDR);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWID(grp_Mem2Stream_fu_102_m_axi_in_V_AWID);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWLEN(grp_Mem2Stream_fu_102_m_axi_in_V_AWLEN);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWSIZE(grp_Mem2Stream_fu_102_m_axi_in_V_AWSIZE);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWBURST(grp_Mem2Stream_fu_102_m_axi_in_V_AWBURST);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWLOCK(grp_Mem2Stream_fu_102_m_axi_in_V_AWLOCK);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWCACHE(grp_Mem2Stream_fu_102_m_axi_in_V_AWCACHE);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWPROT(grp_Mem2Stream_fu_102_m_axi_in_V_AWPROT);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWQOS(grp_Mem2Stream_fu_102_m_axi_in_V_AWQOS);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWREGION(grp_Mem2Stream_fu_102_m_axi_in_V_AWREGION);
    grp_Mem2Stream_fu_102->m_axi_in_V_AWUSER(grp_Mem2Stream_fu_102_m_axi_in_V_AWUSER);
    grp_Mem2Stream_fu_102->m_axi_in_V_WVALID(grp_Mem2Stream_fu_102_m_axi_in_V_WVALID);
    grp_Mem2Stream_fu_102->m_axi_in_V_WREADY(ap_var_for_const0);
    grp_Mem2Stream_fu_102->m_axi_in_V_WDATA(grp_Mem2Stream_fu_102_m_axi_in_V_WDATA);
    grp_Mem2Stream_fu_102->m_axi_in_V_WSTRB(grp_Mem2Stream_fu_102_m_axi_in_V_WSTRB);
    grp_Mem2Stream_fu_102->m_axi_in_V_WLAST(grp_Mem2Stream_fu_102_m_axi_in_V_WLAST);
    grp_Mem2Stream_fu_102->m_axi_in_V_WID(grp_Mem2Stream_fu_102_m_axi_in_V_WID);
    grp_Mem2Stream_fu_102->m_axi_in_V_WUSER(grp_Mem2Stream_fu_102_m_axi_in_V_WUSER);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARVALID(grp_Mem2Stream_fu_102_m_axi_in_V_ARVALID);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARREADY(m_axi_in_V_ARREADY);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARADDR(grp_Mem2Stream_fu_102_m_axi_in_V_ARADDR);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARID(grp_Mem2Stream_fu_102_m_axi_in_V_ARID);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARLEN(grp_Mem2Stream_fu_102_m_axi_in_V_ARLEN);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARSIZE(grp_Mem2Stream_fu_102_m_axi_in_V_ARSIZE);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARBURST(grp_Mem2Stream_fu_102_m_axi_in_V_ARBURST);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARLOCK(grp_Mem2Stream_fu_102_m_axi_in_V_ARLOCK);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARCACHE(grp_Mem2Stream_fu_102_m_axi_in_V_ARCACHE);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARPROT(grp_Mem2Stream_fu_102_m_axi_in_V_ARPROT);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARQOS(grp_Mem2Stream_fu_102_m_axi_in_V_ARQOS);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARREGION(grp_Mem2Stream_fu_102_m_axi_in_V_ARREGION);
    grp_Mem2Stream_fu_102->m_axi_in_V_ARUSER(grp_Mem2Stream_fu_102_m_axi_in_V_ARUSER);
    grp_Mem2Stream_fu_102->m_axi_in_V_RVALID(m_axi_in_V_RVALID);
    grp_Mem2Stream_fu_102->m_axi_in_V_RREADY(grp_Mem2Stream_fu_102_m_axi_in_V_RREADY);
    grp_Mem2Stream_fu_102->m_axi_in_V_RDATA(m_axi_in_V_RDATA);
    grp_Mem2Stream_fu_102->m_axi_in_V_RLAST(m_axi_in_V_RLAST);
    grp_Mem2Stream_fu_102->m_axi_in_V_RID(m_axi_in_V_RID);
    grp_Mem2Stream_fu_102->m_axi_in_V_RUSER(m_axi_in_V_RUSER);
    grp_Mem2Stream_fu_102->m_axi_in_V_RRESP(m_axi_in_V_RRESP);
    grp_Mem2Stream_fu_102->m_axi_in_V_BVALID(ap_var_for_const0);
    grp_Mem2Stream_fu_102->m_axi_in_V_BREADY(grp_Mem2Stream_fu_102_m_axi_in_V_BREADY);
    grp_Mem2Stream_fu_102->m_axi_in_V_BRESP(ap_var_for_const1);
    grp_Mem2Stream_fu_102->m_axi_in_V_BID(ap_var_for_const2);
    grp_Mem2Stream_fu_102->m_axi_in_V_BUSER(ap_var_for_const2);
    grp_Mem2Stream_fu_102->in_V1(in_V1);
    grp_Mem2Stream_fu_102->tmp_8(tmp_5_i_i_i_i_reg_200);
    grp_Mem2Stream_fu_102->out_V_V_din(grp_Mem2Stream_fu_102_out_V_V_din);
    grp_Mem2Stream_fu_102->out_V_V_full_n(memInStrm_V_V_full_n);
    grp_Mem2Stream_fu_102->out_V_V_write(grp_Mem2Stream_fu_102_out_V_V_write);
    BlackBoxJam_mul_5bkb_U9 = new BlackBoxJam_mul_5bkb<1,5,5,32,32>("BlackBoxJam_mul_5bkb_U9");
    BlackBoxJam_mul_5bkb_U9->clk(ap_clk);
    BlackBoxJam_mul_5bkb_U9->reset(ap_rst);
    BlackBoxJam_mul_5bkb_U9->din0(grp_fu_140_p0);
    BlackBoxJam_mul_5bkb_U9->din1(rep_fu_54);
    BlackBoxJam_mul_5bkb_U9->ce(ap_var_for_const3);
    BlackBoxJam_mul_5bkb_U9->dout(grp_fu_140_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_119);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( numReps_channel_full_n );
    sensitive << ( out_V3_out_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i_i_i_i_fu_120_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i_i_i_i_fu_120_p2 );

    SC_METHOD(thread_grp_Mem2Stream_1_fu_92_ap_start);
    sensitive << ( ap_reg_grp_Mem2Stream_1_fu_92_ap_start );

    SC_METHOD(thread_grp_Mem2Stream_fu_102_ap_start);
    sensitive << ( ap_reg_grp_Mem2Stream_fu_102_ap_start );

    SC_METHOD(thread_grp_fu_140_p0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_m_axi_in_V_ARADDR);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARADDR );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARADDR );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARBURST);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARBURST );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARBURST );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARCACHE);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARCACHE );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARCACHE );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARID);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARID );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARID );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARLEN);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLEN );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARLEN );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARLOCK);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLOCK );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARLOCK );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARPROT);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARPROT );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARPROT );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARQOS);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARQOS );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARQOS );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARREGION);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARREGION );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARREGION );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARSIZE);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARSIZE );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARSIZE );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARUSER);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARUSER );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARUSER );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_ARVALID);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_ARVALID );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_ARVALID );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_AWADDR);

    SC_METHOD(thread_m_axi_in_V_AWBURST);

    SC_METHOD(thread_m_axi_in_V_AWCACHE);

    SC_METHOD(thread_m_axi_in_V_AWID);

    SC_METHOD(thread_m_axi_in_V_AWLEN);

    SC_METHOD(thread_m_axi_in_V_AWLOCK);

    SC_METHOD(thread_m_axi_in_V_AWPROT);

    SC_METHOD(thread_m_axi_in_V_AWQOS);

    SC_METHOD(thread_m_axi_in_V_AWREGION);

    SC_METHOD(thread_m_axi_in_V_AWSIZE);

    SC_METHOD(thread_m_axi_in_V_AWUSER);

    SC_METHOD(thread_m_axi_in_V_AWVALID);

    SC_METHOD(thread_m_axi_in_V_BREADY);

    SC_METHOD(thread_m_axi_in_V_RREADY);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_m_axi_in_V_RREADY );
    sensitive << ( grp_Mem2Stream_fu_102_m_axi_in_V_RREADY );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_m_axi_in_V_WDATA);

    SC_METHOD(thread_m_axi_in_V_WID);

    SC_METHOD(thread_m_axi_in_V_WLAST);

    SC_METHOD(thread_m_axi_in_V_WSTRB);

    SC_METHOD(thread_m_axi_in_V_WUSER);

    SC_METHOD(thread_m_axi_in_V_WVALID);

    SC_METHOD(thread_memInStrm_V_V_din);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_out_V_V_din );
    sensitive << ( grp_Mem2Stream_fu_102_out_V_V_din );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_memInStrm_V_V_write);
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( grp_Mem2Stream_1_fu_92_out_V_V_write );
    sensitive << ( grp_Mem2Stream_fu_102_out_V_V_write );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_numReps_channel_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps_channel_full_n );

    SC_METHOD(thread_numReps_channel_din);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( numReps );
    sensitive << ( ap_condition_119 );

    SC_METHOD(thread_numReps_channel_write);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_condition_119 );

    SC_METHOD(thread_out_V3_out_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_V3_out_full_n );

    SC_METHOD(thread_out_V3_out_din);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_V3 );
    sensitive << ( ap_condition_119 );

    SC_METHOD(thread_out_V3_out_write);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_condition_119 );

    SC_METHOD(thread_rep_3_fu_156_p2);
    sensitive << ( rep_load_reg_186 );

    SC_METHOD(thread_rep_4_fu_146_p2);
    sensitive << ( rep_load_reg_186 );

    SC_METHOD(thread_repsLeft_fu_125_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( rep_fu_54 );

    SC_METHOD(thread_repsLeft_fu_125_p2);
    sensitive << ( numReps );
    sensitive << ( repsLeft_fu_125_p1 );

    SC_METHOD(thread_tmp_4_i_i_i_i_fu_134_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i_i_i_i_fu_120_p2 );
    sensitive << ( tmp_fu_130_p1 );

    SC_METHOD(thread_tmp_fu_130_p1);
    sensitive << ( repsLeft_fu_125_p2 );

    SC_METHOD(thread_tmp_i_i_i_i_fu_120_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( rep_fu_54 );

    SC_METHOD(thread_tmp_i_i_i_i_fu_120_p2);
    sensitive << ( numReps );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i_i_i_i_fu_120_p0 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_condition_119 );
    sensitive << ( tmp_4_i_i_i_i_reg_196 );
    sensitive << ( tmp_i_i_i_i_fu_120_p2 );
    sensitive << ( grp_Mem2Stream_1_fu_92_ap_done );
    sensitive << ( grp_Mem2Stream_fu_102_ap_done );

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const1);

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000001";
    ap_reg_grp_Mem2Stream_1_fu_92_ap_start = SC_LOGIC_0;
    ap_reg_grp_Mem2Stream_fu_102_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Mem2Stream_Batch12_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, m_axi_in_V_AWVALID, "(port)m_axi_in_V_AWVALID");
    sc_trace(mVcdFile, m_axi_in_V_AWREADY, "(port)m_axi_in_V_AWREADY");
    sc_trace(mVcdFile, m_axi_in_V_AWADDR, "(port)m_axi_in_V_AWADDR");
    sc_trace(mVcdFile, m_axi_in_V_AWID, "(port)m_axi_in_V_AWID");
    sc_trace(mVcdFile, m_axi_in_V_AWLEN, "(port)m_axi_in_V_AWLEN");
    sc_trace(mVcdFile, m_axi_in_V_AWSIZE, "(port)m_axi_in_V_AWSIZE");
    sc_trace(mVcdFile, m_axi_in_V_AWBURST, "(port)m_axi_in_V_AWBURST");
    sc_trace(mVcdFile, m_axi_in_V_AWLOCK, "(port)m_axi_in_V_AWLOCK");
    sc_trace(mVcdFile, m_axi_in_V_AWCACHE, "(port)m_axi_in_V_AWCACHE");
    sc_trace(mVcdFile, m_axi_in_V_AWPROT, "(port)m_axi_in_V_AWPROT");
    sc_trace(mVcdFile, m_axi_in_V_AWQOS, "(port)m_axi_in_V_AWQOS");
    sc_trace(mVcdFile, m_axi_in_V_AWREGION, "(port)m_axi_in_V_AWREGION");
    sc_trace(mVcdFile, m_axi_in_V_AWUSER, "(port)m_axi_in_V_AWUSER");
    sc_trace(mVcdFile, m_axi_in_V_WVALID, "(port)m_axi_in_V_WVALID");
    sc_trace(mVcdFile, m_axi_in_V_WREADY, "(port)m_axi_in_V_WREADY");
    sc_trace(mVcdFile, m_axi_in_V_WDATA, "(port)m_axi_in_V_WDATA");
    sc_trace(mVcdFile, m_axi_in_V_WSTRB, "(port)m_axi_in_V_WSTRB");
    sc_trace(mVcdFile, m_axi_in_V_WLAST, "(port)m_axi_in_V_WLAST");
    sc_trace(mVcdFile, m_axi_in_V_WID, "(port)m_axi_in_V_WID");
    sc_trace(mVcdFile, m_axi_in_V_WUSER, "(port)m_axi_in_V_WUSER");
    sc_trace(mVcdFile, m_axi_in_V_ARVALID, "(port)m_axi_in_V_ARVALID");
    sc_trace(mVcdFile, m_axi_in_V_ARREADY, "(port)m_axi_in_V_ARREADY");
    sc_trace(mVcdFile, m_axi_in_V_ARADDR, "(port)m_axi_in_V_ARADDR");
    sc_trace(mVcdFile, m_axi_in_V_ARID, "(port)m_axi_in_V_ARID");
    sc_trace(mVcdFile, m_axi_in_V_ARLEN, "(port)m_axi_in_V_ARLEN");
    sc_trace(mVcdFile, m_axi_in_V_ARSIZE, "(port)m_axi_in_V_ARSIZE");
    sc_trace(mVcdFile, m_axi_in_V_ARBURST, "(port)m_axi_in_V_ARBURST");
    sc_trace(mVcdFile, m_axi_in_V_ARLOCK, "(port)m_axi_in_V_ARLOCK");
    sc_trace(mVcdFile, m_axi_in_V_ARCACHE, "(port)m_axi_in_V_ARCACHE");
    sc_trace(mVcdFile, m_axi_in_V_ARPROT, "(port)m_axi_in_V_ARPROT");
    sc_trace(mVcdFile, m_axi_in_V_ARQOS, "(port)m_axi_in_V_ARQOS");
    sc_trace(mVcdFile, m_axi_in_V_ARREGION, "(port)m_axi_in_V_ARREGION");
    sc_trace(mVcdFile, m_axi_in_V_ARUSER, "(port)m_axi_in_V_ARUSER");
    sc_trace(mVcdFile, m_axi_in_V_RVALID, "(port)m_axi_in_V_RVALID");
    sc_trace(mVcdFile, m_axi_in_V_RREADY, "(port)m_axi_in_V_RREADY");
    sc_trace(mVcdFile, m_axi_in_V_RDATA, "(port)m_axi_in_V_RDATA");
    sc_trace(mVcdFile, m_axi_in_V_RLAST, "(port)m_axi_in_V_RLAST");
    sc_trace(mVcdFile, m_axi_in_V_RID, "(port)m_axi_in_V_RID");
    sc_trace(mVcdFile, m_axi_in_V_RUSER, "(port)m_axi_in_V_RUSER");
    sc_trace(mVcdFile, m_axi_in_V_RRESP, "(port)m_axi_in_V_RRESP");
    sc_trace(mVcdFile, m_axi_in_V_BVALID, "(port)m_axi_in_V_BVALID");
    sc_trace(mVcdFile, m_axi_in_V_BREADY, "(port)m_axi_in_V_BREADY");
    sc_trace(mVcdFile, m_axi_in_V_BRESP, "(port)m_axi_in_V_BRESP");
    sc_trace(mVcdFile, m_axi_in_V_BID, "(port)m_axi_in_V_BID");
    sc_trace(mVcdFile, m_axi_in_V_BUSER, "(port)m_axi_in_V_BUSER");
    sc_trace(mVcdFile, in_V1, "(port)in_V1");
    sc_trace(mVcdFile, memInStrm_V_V_din, "(port)memInStrm_V_V_din");
    sc_trace(mVcdFile, memInStrm_V_V_full_n, "(port)memInStrm_V_V_full_n");
    sc_trace(mVcdFile, memInStrm_V_V_write, "(port)memInStrm_V_V_write");
    sc_trace(mVcdFile, numReps, "(port)numReps");
    sc_trace(mVcdFile, numReps_channel_din, "(port)numReps_channel_din");
    sc_trace(mVcdFile, numReps_channel_full_n, "(port)numReps_channel_full_n");
    sc_trace(mVcdFile, numReps_channel_write, "(port)numReps_channel_write");
    sc_trace(mVcdFile, out_V3, "(port)out_V3");
    sc_trace(mVcdFile, out_V3_out_din, "(port)out_V3_out_din");
    sc_trace(mVcdFile, out_V3_out_full_n, "(port)out_V3_out_full_n");
    sc_trace(mVcdFile, out_V3_out_write, "(port)out_V3_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, numReps_channel_blk_n, "numReps_channel_blk_n");
    sc_trace(mVcdFile, out_V3_out_blk_n, "out_V3_out_blk_n");
    sc_trace(mVcdFile, ap_condition_119, "ap_condition_119");
    sc_trace(mVcdFile, rep_load_reg_186, "rep_load_reg_186");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_4_i_i_i_i_fu_134_p2, "tmp_4_i_i_i_i_fu_134_p2");
    sc_trace(mVcdFile, tmp_4_i_i_i_i_reg_196, "tmp_4_i_i_i_i_reg_196");
    sc_trace(mVcdFile, tmp_i_i_i_i_fu_120_p2, "tmp_i_i_i_i_fu_120_p2");
    sc_trace(mVcdFile, grp_fu_140_p2, "grp_fu_140_p2");
    sc_trace(mVcdFile, tmp_5_i_i_i_i_reg_200, "tmp_5_i_i_i_i_reg_200");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_ap_start, "grp_Mem2Stream_1_fu_92_ap_start");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_ap_done, "grp_Mem2Stream_1_fu_92_ap_done");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_ap_idle, "grp_Mem2Stream_1_fu_92_ap_idle");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_ap_ready, "grp_Mem2Stream_1_fu_92_ap_ready");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWVALID, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWVALID");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWADDR, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWADDR");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWID, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWID");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWLEN, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWLEN");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWSIZE, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWSIZE");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWBURST, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWBURST");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWLOCK, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWLOCK");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWCACHE, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWCACHE");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWPROT, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWPROT");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWQOS, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWQOS");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWREGION, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWREGION");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_AWUSER, "grp_Mem2Stream_1_fu_92_m_axi_in_V_AWUSER");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_WVALID, "grp_Mem2Stream_1_fu_92_m_axi_in_V_WVALID");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_WDATA, "grp_Mem2Stream_1_fu_92_m_axi_in_V_WDATA");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_WSTRB, "grp_Mem2Stream_1_fu_92_m_axi_in_V_WSTRB");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_WLAST, "grp_Mem2Stream_1_fu_92_m_axi_in_V_WLAST");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_WID, "grp_Mem2Stream_1_fu_92_m_axi_in_V_WID");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_WUSER, "grp_Mem2Stream_1_fu_92_m_axi_in_V_WUSER");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARVALID, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARVALID");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARADDR, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARADDR");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARID, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARID");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLEN, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLEN");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARSIZE, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARSIZE");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARBURST, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARBURST");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLOCK, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLOCK");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARCACHE, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARCACHE");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARPROT, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARPROT");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARQOS, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARQOS");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARREGION, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARREGION");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_ARUSER, "grp_Mem2Stream_1_fu_92_m_axi_in_V_ARUSER");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_RREADY, "grp_Mem2Stream_1_fu_92_m_axi_in_V_RREADY");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_m_axi_in_V_BREADY, "grp_Mem2Stream_1_fu_92_m_axi_in_V_BREADY");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_out_V_V_din, "grp_Mem2Stream_1_fu_92_out_V_V_din");
    sc_trace(mVcdFile, grp_Mem2Stream_1_fu_92_out_V_V_write, "grp_Mem2Stream_1_fu_92_out_V_V_write");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_ap_start, "grp_Mem2Stream_fu_102_ap_start");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_ap_done, "grp_Mem2Stream_fu_102_ap_done");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_ap_idle, "grp_Mem2Stream_fu_102_ap_idle");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_ap_ready, "grp_Mem2Stream_fu_102_ap_ready");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWVALID, "grp_Mem2Stream_fu_102_m_axi_in_V_AWVALID");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWADDR, "grp_Mem2Stream_fu_102_m_axi_in_V_AWADDR");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWID, "grp_Mem2Stream_fu_102_m_axi_in_V_AWID");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWLEN, "grp_Mem2Stream_fu_102_m_axi_in_V_AWLEN");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWSIZE, "grp_Mem2Stream_fu_102_m_axi_in_V_AWSIZE");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWBURST, "grp_Mem2Stream_fu_102_m_axi_in_V_AWBURST");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWLOCK, "grp_Mem2Stream_fu_102_m_axi_in_V_AWLOCK");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWCACHE, "grp_Mem2Stream_fu_102_m_axi_in_V_AWCACHE");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWPROT, "grp_Mem2Stream_fu_102_m_axi_in_V_AWPROT");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWQOS, "grp_Mem2Stream_fu_102_m_axi_in_V_AWQOS");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWREGION, "grp_Mem2Stream_fu_102_m_axi_in_V_AWREGION");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_AWUSER, "grp_Mem2Stream_fu_102_m_axi_in_V_AWUSER");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_WVALID, "grp_Mem2Stream_fu_102_m_axi_in_V_WVALID");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_WDATA, "grp_Mem2Stream_fu_102_m_axi_in_V_WDATA");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_WSTRB, "grp_Mem2Stream_fu_102_m_axi_in_V_WSTRB");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_WLAST, "grp_Mem2Stream_fu_102_m_axi_in_V_WLAST");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_WID, "grp_Mem2Stream_fu_102_m_axi_in_V_WID");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_WUSER, "grp_Mem2Stream_fu_102_m_axi_in_V_WUSER");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARVALID, "grp_Mem2Stream_fu_102_m_axi_in_V_ARVALID");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARADDR, "grp_Mem2Stream_fu_102_m_axi_in_V_ARADDR");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARID, "grp_Mem2Stream_fu_102_m_axi_in_V_ARID");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARLEN, "grp_Mem2Stream_fu_102_m_axi_in_V_ARLEN");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARSIZE, "grp_Mem2Stream_fu_102_m_axi_in_V_ARSIZE");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARBURST, "grp_Mem2Stream_fu_102_m_axi_in_V_ARBURST");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARLOCK, "grp_Mem2Stream_fu_102_m_axi_in_V_ARLOCK");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARCACHE, "grp_Mem2Stream_fu_102_m_axi_in_V_ARCACHE");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARPROT, "grp_Mem2Stream_fu_102_m_axi_in_V_ARPROT");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARQOS, "grp_Mem2Stream_fu_102_m_axi_in_V_ARQOS");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARREGION, "grp_Mem2Stream_fu_102_m_axi_in_V_ARREGION");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_ARUSER, "grp_Mem2Stream_fu_102_m_axi_in_V_ARUSER");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_RREADY, "grp_Mem2Stream_fu_102_m_axi_in_V_RREADY");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_m_axi_in_V_BREADY, "grp_Mem2Stream_fu_102_m_axi_in_V_BREADY");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_out_V_V_din, "grp_Mem2Stream_fu_102_out_V_V_din");
    sc_trace(mVcdFile, grp_Mem2Stream_fu_102_out_V_V_write, "grp_Mem2Stream_fu_102_out_V_V_write");
    sc_trace(mVcdFile, ap_reg_grp_Mem2Stream_1_fu_92_ap_start, "ap_reg_grp_Mem2Stream_1_fu_92_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_reg_grp_Mem2Stream_fu_102_ap_start, "ap_reg_grp_Mem2Stream_fu_102_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, rep_fu_54, "rep_fu_54");
    sc_trace(mVcdFile, rep_4_fu_146_p2, "rep_4_fu_146_p2");
    sc_trace(mVcdFile, rep_3_fu_156_p2, "rep_3_fu_156_p2");
    sc_trace(mVcdFile, tmp_i_i_i_i_fu_120_p0, "tmp_i_i_i_i_fu_120_p0");
    sc_trace(mVcdFile, repsLeft_fu_125_p1, "repsLeft_fu_125_p1");
    sc_trace(mVcdFile, repsLeft_fu_125_p2, "repsLeft_fu_125_p2");
    sc_trace(mVcdFile, tmp_fu_130_p1, "tmp_fu_130_p1");
    sc_trace(mVcdFile, grp_fu_140_p0, "grp_fu_140_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

Mem2Stream_Batch12::~Mem2Stream_Batch12() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_Mem2Stream_1_fu_92;
    delete grp_Mem2Stream_fu_102;
    delete BlackBoxJam_mul_5bkb_U9;
}

void Mem2Stream_Batch12::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_logic_1;
}

void Mem2Stream_Batch12::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_0;
}

void Mem2Stream_Batch12::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv1_0;
}

void Mem2Stream_Batch12::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv2_0;
}

void Mem2Stream_Batch12::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_i_i_i_fu_120_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_Mem2Stream_1_fu_92_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()))) {
            ap_reg_grp_Mem2Stream_1_fu_92_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Mem2Stream_1_fu_92_ap_ready.read())) {
            ap_reg_grp_Mem2Stream_1_fu_92_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_Mem2Stream_fu_102_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
            ap_reg_grp_Mem2Stream_fu_102_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Mem2Stream_fu_102_ap_ready.read())) {
            ap_reg_grp_Mem2Stream_fu_102_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read()))) {
        rep_fu_54 = rep_3_fu_156_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read()))) {
        rep_fu_54 = rep_4_fu_146_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_condition_119.read(), ap_const_boolean_1))) {
        rep_fu_54 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        rep_load_reg_186 = rep_fu_54.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_i_i_i_fu_120_p2.read()))) {
        tmp_4_i_i_i_i_reg_196 = tmp_4_i_i_i_i_fu_134_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        tmp_5_i_i_i_i_reg_200 = grp_fu_140_p2.read();
    }
}

void Mem2Stream_Batch12::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void Mem2Stream_Batch12::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void Mem2Stream_Batch12::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read().range(5, 5);
}

void Mem2Stream_Batch12::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(6, 6);
}

void Mem2Stream_Batch12::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(7, 7);
}

void Mem2Stream_Batch12::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read().range(8, 8);
}

void Mem2Stream_Batch12::thread_ap_condition_119() {
    ap_condition_119 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(out_V3_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(numReps_channel_full_n.read(), ap_const_logic_0));
}

void Mem2Stream_Batch12::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_i_i_i_fu_120_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void Mem2Stream_Batch12::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Mem2Stream_Batch12::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_i_i_i_fu_120_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void Mem2Stream_Batch12::thread_grp_Mem2Stream_1_fu_92_ap_start() {
    grp_Mem2Stream_1_fu_92_ap_start = ap_reg_grp_Mem2Stream_1_fu_92_ap_start.read();
}

void Mem2Stream_Batch12::thread_grp_Mem2Stream_fu_102_ap_start() {
    grp_Mem2Stream_fu_102_ap_start = ap_reg_grp_Mem2Stream_fu_102_ap_start.read();
}

void Mem2Stream_Batch12::thread_grp_fu_140_p0() {
    grp_fu_140_p0 =  (sc_lv<5>) (ap_const_lv32_D);
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARADDR() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARADDR = grp_Mem2Stream_fu_102_m_axi_in_V_ARADDR.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARADDR = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARADDR.read();
    } else {
        m_axi_in_V_ARADDR = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARBURST() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARBURST = grp_Mem2Stream_fu_102_m_axi_in_V_ARBURST.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARBURST = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARBURST.read();
    } else {
        m_axi_in_V_ARBURST =  (sc_lv<2>) ("XX");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARCACHE() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARCACHE = grp_Mem2Stream_fu_102_m_axi_in_V_ARCACHE.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARCACHE = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARCACHE.read();
    } else {
        m_axi_in_V_ARCACHE =  (sc_lv<4>) ("XXXX");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARID() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARID = grp_Mem2Stream_fu_102_m_axi_in_V_ARID.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARID = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARID.read();
    } else {
        m_axi_in_V_ARID =  (sc_lv<1>) ("X");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARLEN() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARLEN = grp_Mem2Stream_fu_102_m_axi_in_V_ARLEN.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARLEN = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLEN.read();
    } else {
        m_axi_in_V_ARLEN =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARLOCK() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARLOCK = grp_Mem2Stream_fu_102_m_axi_in_V_ARLOCK.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARLOCK = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARLOCK.read();
    } else {
        m_axi_in_V_ARLOCK =  (sc_lv<2>) ("XX");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARPROT() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARPROT = grp_Mem2Stream_fu_102_m_axi_in_V_ARPROT.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARPROT = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARPROT.read();
    } else {
        m_axi_in_V_ARPROT =  (sc_lv<3>) ("XXX");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARQOS() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARQOS = grp_Mem2Stream_fu_102_m_axi_in_V_ARQOS.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARQOS = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARQOS.read();
    } else {
        m_axi_in_V_ARQOS =  (sc_lv<4>) ("XXXX");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARREGION() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARREGION = grp_Mem2Stream_fu_102_m_axi_in_V_ARREGION.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARREGION = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARREGION.read();
    } else {
        m_axi_in_V_ARREGION =  (sc_lv<4>) ("XXXX");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARSIZE() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARSIZE = grp_Mem2Stream_fu_102_m_axi_in_V_ARSIZE.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARSIZE = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARSIZE.read();
    } else {
        m_axi_in_V_ARSIZE =  (sc_lv<3>) ("XXX");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARUSER() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARUSER = grp_Mem2Stream_fu_102_m_axi_in_V_ARUSER.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARUSER = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARUSER.read();
    } else {
        m_axi_in_V_ARUSER =  (sc_lv<1>) ("X");
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_ARVALID() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARVALID = grp_Mem2Stream_fu_102_m_axi_in_V_ARVALID.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_ARVALID = grp_Mem2Stream_1_fu_92_m_axi_in_V_ARVALID.read();
    } else {
        m_axi_in_V_ARVALID = ap_const_logic_0;
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWADDR() {
    m_axi_in_V_AWADDR = ap_const_lv64_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWBURST() {
    m_axi_in_V_AWBURST = ap_const_lv2_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWCACHE() {
    m_axi_in_V_AWCACHE = ap_const_lv4_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWID() {
    m_axi_in_V_AWID = ap_const_lv1_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWLEN() {
    m_axi_in_V_AWLEN = ap_const_lv32_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWLOCK() {
    m_axi_in_V_AWLOCK = ap_const_lv2_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWPROT() {
    m_axi_in_V_AWPROT = ap_const_lv3_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWQOS() {
    m_axi_in_V_AWQOS = ap_const_lv4_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWREGION() {
    m_axi_in_V_AWREGION = ap_const_lv4_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWSIZE() {
    m_axi_in_V_AWSIZE = ap_const_lv3_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWUSER() {
    m_axi_in_V_AWUSER = ap_const_lv1_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_AWVALID() {
    m_axi_in_V_AWVALID = ap_const_logic_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_BREADY() {
    m_axi_in_V_BREADY = ap_const_logic_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_RREADY() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_RREADY = grp_Mem2Stream_fu_102_m_axi_in_V_RREADY.read();
    } else if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read())) || 
                (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                 !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())))) {
        m_axi_in_V_RREADY = grp_Mem2Stream_1_fu_92_m_axi_in_V_RREADY.read();
    } else {
        m_axi_in_V_RREADY = ap_const_logic_0;
    }
}

void Mem2Stream_Batch12::thread_m_axi_in_V_WDATA() {
    m_axi_in_V_WDATA = ap_const_lv64_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_WID() {
    m_axi_in_V_WID = ap_const_lv1_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_WLAST() {
    m_axi_in_V_WLAST = ap_const_logic_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_WSTRB() {
    m_axi_in_V_WSTRB = ap_const_lv8_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_WUSER() {
    m_axi_in_V_WUSER = ap_const_lv1_0;
}

void Mem2Stream_Batch12::thread_m_axi_in_V_WVALID() {
    m_axi_in_V_WVALID = ap_const_logic_0;
}

void Mem2Stream_Batch12::thread_memInStrm_V_V_din() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())) {
            memInStrm_V_V_din = grp_Mem2Stream_fu_102_out_V_V_din.read();
        } else if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())) {
            memInStrm_V_V_din = grp_Mem2Stream_1_fu_92_out_V_V_din.read();
        } else {
            memInStrm_V_V_din = grp_Mem2Stream_fu_102_out_V_V_din.read();
        }
    } else {
        memInStrm_V_V_din = grp_Mem2Stream_fu_102_out_V_V_din.read();
    }
}

void Mem2Stream_Batch12::thread_memInStrm_V_V_write() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read())) {
        if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())) {
            memInStrm_V_V_write = grp_Mem2Stream_fu_102_out_V_V_write.read();
        } else if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())) {
            memInStrm_V_V_write = grp_Mem2Stream_1_fu_92_out_V_V_write.read();
        } else {
            memInStrm_V_V_write = ap_const_logic_0;
        }
    } else {
        memInStrm_V_V_write = ap_const_logic_0;
    }
}

void Mem2Stream_Batch12::thread_numReps_channel_blk_n() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        numReps_channel_blk_n = numReps_channel_full_n.read();
    } else {
        numReps_channel_blk_n = ap_const_logic_1;
    }
}

void Mem2Stream_Batch12::thread_numReps_channel_din() {
    numReps_channel_din = numReps.read();
}

void Mem2Stream_Batch12::thread_numReps_channel_write() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_condition_119.read(), ap_const_boolean_1))) {
        numReps_channel_write = ap_const_logic_1;
    } else {
        numReps_channel_write = ap_const_logic_0;
    }
}

void Mem2Stream_Batch12::thread_out_V3_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        out_V3_out_blk_n = out_V3_out_full_n.read();
    } else {
        out_V3_out_blk_n = ap_const_logic_1;
    }
}

void Mem2Stream_Batch12::thread_out_V3_out_din() {
    out_V3_out_din = out_V3.read();
}

void Mem2Stream_Batch12::thread_out_V3_out_write() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_condition_119.read(), ap_const_boolean_1))) {
        out_V3_out_write = ap_const_logic_1;
    } else {
        out_V3_out_write = ap_const_logic_0;
    }
}

void Mem2Stream_Batch12::thread_rep_3_fu_156_p2() {
    rep_3_fu_156_p2 = (!rep_load_reg_186.read().is_01() || !ap_const_lv32_10.is_01())? sc_lv<32>(): (sc_bigint<32>(rep_load_reg_186.read()) + sc_biguint<32>(ap_const_lv32_10));
}

void Mem2Stream_Batch12::thread_rep_4_fu_146_p2() {
    rep_4_fu_146_p2 = (!rep_load_reg_186.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_bigint<32>(rep_load_reg_186.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void Mem2Stream_Batch12::thread_repsLeft_fu_125_p1() {
    repsLeft_fu_125_p1 = rep_fu_54.read();
}

void Mem2Stream_Batch12::thread_repsLeft_fu_125_p2() {
    repsLeft_fu_125_p2 = (!numReps.read().is_01() || !repsLeft_fu_125_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(numReps.read()) - sc_bigint<32>(repsLeft_fu_125_p1.read()));
}

void Mem2Stream_Batch12::thread_tmp_4_i_i_i_i_fu_134_p2() {
    tmp_4_i_i_i_i_fu_134_p2 = (!tmp_fu_130_p1.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_130_p1.read() == ap_const_lv4_0);
}

void Mem2Stream_Batch12::thread_tmp_fu_130_p1() {
    tmp_fu_130_p1 = repsLeft_fu_125_p2.read().range(4-1, 0);
}

void Mem2Stream_Batch12::thread_tmp_i_i_i_i_fu_120_p0() {
    tmp_i_i_i_i_fu_120_p0 = rep_fu_54.read();
}

void Mem2Stream_Batch12::thread_tmp_i_i_i_i_fu_120_p2() {
    tmp_i_i_i_i_fu_120_p2 = (!tmp_i_i_i_i_fu_120_p0.read().is_01() || !numReps.read().is_01())? sc_lv<1>(): sc_lv<1>(tmp_i_i_i_i_fu_120_p0.read() == numReps.read());
}

void Mem2Stream_Batch12::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_condition_119.read(), ap_const_boolean_1)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_i_i_i_i_fu_120_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read())) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if (!((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_Mem2Stream_fu_102_ap_done.read())) || (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_4_i_i_i_i_reg_196.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, grp_Mem2Stream_1_fu_92_ap_done.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

