// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _Stream2Mem_Batch_HH_
#define _Stream2Mem_Batch_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Stream2Mem.h"
#include "Stream2Mem_64u_8u_s.h"

namespace ap_rtl {

struct Stream2Mem_Batch : public sc_module {
    // Port declarations 61
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<64> > memOutStrm_V_V_dout;
    sc_in< sc_logic > memOutStrm_V_V_empty_n;
    sc_out< sc_logic > memOutStrm_V_V_read;
    sc_out< sc_logic > m_axi_in_V_AWVALID;
    sc_in< sc_logic > m_axi_in_V_AWREADY;
    sc_out< sc_lv<64> > m_axi_in_V_AWADDR;
    sc_out< sc_lv<1> > m_axi_in_V_AWID;
    sc_out< sc_lv<32> > m_axi_in_V_AWLEN;
    sc_out< sc_lv<3> > m_axi_in_V_AWSIZE;
    sc_out< sc_lv<2> > m_axi_in_V_AWBURST;
    sc_out< sc_lv<2> > m_axi_in_V_AWLOCK;
    sc_out< sc_lv<4> > m_axi_in_V_AWCACHE;
    sc_out< sc_lv<3> > m_axi_in_V_AWPROT;
    sc_out< sc_lv<4> > m_axi_in_V_AWQOS;
    sc_out< sc_lv<4> > m_axi_in_V_AWREGION;
    sc_out< sc_lv<1> > m_axi_in_V_AWUSER;
    sc_out< sc_logic > m_axi_in_V_WVALID;
    sc_in< sc_logic > m_axi_in_V_WREADY;
    sc_out< sc_lv<64> > m_axi_in_V_WDATA;
    sc_out< sc_lv<8> > m_axi_in_V_WSTRB;
    sc_out< sc_logic > m_axi_in_V_WLAST;
    sc_out< sc_lv<1> > m_axi_in_V_WID;
    sc_out< sc_lv<1> > m_axi_in_V_WUSER;
    sc_out< sc_logic > m_axi_in_V_ARVALID;
    sc_in< sc_logic > m_axi_in_V_ARREADY;
    sc_out< sc_lv<64> > m_axi_in_V_ARADDR;
    sc_out< sc_lv<1> > m_axi_in_V_ARID;
    sc_out< sc_lv<32> > m_axi_in_V_ARLEN;
    sc_out< sc_lv<3> > m_axi_in_V_ARSIZE;
    sc_out< sc_lv<2> > m_axi_in_V_ARBURST;
    sc_out< sc_lv<2> > m_axi_in_V_ARLOCK;
    sc_out< sc_lv<4> > m_axi_in_V_ARCACHE;
    sc_out< sc_lv<3> > m_axi_in_V_ARPROT;
    sc_out< sc_lv<4> > m_axi_in_V_ARQOS;
    sc_out< sc_lv<4> > m_axi_in_V_ARREGION;
    sc_out< sc_lv<1> > m_axi_in_V_ARUSER;
    sc_in< sc_logic > m_axi_in_V_RVALID;
    sc_out< sc_logic > m_axi_in_V_RREADY;
    sc_in< sc_lv<64> > m_axi_in_V_RDATA;
    sc_in< sc_logic > m_axi_in_V_RLAST;
    sc_in< sc_lv<1> > m_axi_in_V_RID;
    sc_in< sc_lv<1> > m_axi_in_V_RUSER;
    sc_in< sc_lv<2> > m_axi_in_V_RRESP;
    sc_in< sc_logic > m_axi_in_V_BVALID;
    sc_out< sc_logic > m_axi_in_V_BREADY;
    sc_in< sc_lv<2> > m_axi_in_V_BRESP;
    sc_in< sc_lv<1> > m_axi_in_V_BID;
    sc_in< sc_lv<1> > m_axi_in_V_BUSER;
    sc_in< sc_lv<61> > out_V3_dout;
    sc_in< sc_logic > out_V3_empty_n;
    sc_out< sc_logic > out_V3_read;
    sc_in< sc_lv<32> > numReps_channel22_dout;
    sc_in< sc_logic > numReps_channel22_empty_n;
    sc_out< sc_logic > numReps_channel22_read;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;
    sc_signal< sc_lv<1> > ap_var_for_const2;
    sc_signal< sc_lv<2> > ap_var_for_const3;


    // Module declarations
    Stream2Mem_Batch(sc_module_name name);
    SC_HAS_PROCESS(Stream2Mem_Batch);

    ~Stream2Mem_Batch();

    sc_trace_file* mVcdFile;

    Stream2Mem* grp_Stream2Mem_fu_58;
    Stream2Mem_64u_8u_s* grp_Stream2Mem_64u_8u_s_fu_68;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_in_V_V_blk_n;
    sc_signal< sc_logic > memOutStrm_V_V_blk_n;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > ap_CS_fsm_state10;
    sc_signal< sc_lv<1> > tmp_1_i_i_i_reg_158;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_out_V_blk_n_AW;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_out_V_blk_n_W;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_out_V_blk_n_B;
    sc_signal< sc_logic > in_V_blk_n_AW;
    sc_signal< sc_logic > in_V_blk_n_W;
    sc_signal< sc_logic > in_V_blk_n_B;
    sc_signal< sc_logic > out_V3_blk_n;
    sc_signal< sc_logic > numReps_channel22_blk_n;
    sc_signal< sc_lv<61> > out_V3_read_reg_135;
    sc_signal< bool > ap_condition_148;
    sc_signal< sc_lv<32> > numReps_channel22_re_reg_141;
    sc_signal< sc_lv<32> > rep_load_reg_147;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > tmp_1_i_i_i_fu_101_p2;
    sc_signal< sc_lv<1> > tmp_i_i_i_fu_87_p2;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_ap_start;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_ap_done;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_ap_idle;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_ap_ready;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_in_V_V_read;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_m_axi_out_V_AWVALID;
    sc_signal< sc_lv<64> > grp_Stream2Mem_fu_58_m_axi_out_V_AWADDR;
    sc_signal< sc_lv<1> > grp_Stream2Mem_fu_58_m_axi_out_V_AWID;
    sc_signal< sc_lv<32> > grp_Stream2Mem_fu_58_m_axi_out_V_AWLEN;
    sc_signal< sc_lv<3> > grp_Stream2Mem_fu_58_m_axi_out_V_AWSIZE;
    sc_signal< sc_lv<2> > grp_Stream2Mem_fu_58_m_axi_out_V_AWBURST;
    sc_signal< sc_lv<2> > grp_Stream2Mem_fu_58_m_axi_out_V_AWLOCK;
    sc_signal< sc_lv<4> > grp_Stream2Mem_fu_58_m_axi_out_V_AWCACHE;
    sc_signal< sc_lv<3> > grp_Stream2Mem_fu_58_m_axi_out_V_AWPROT;
    sc_signal< sc_lv<4> > grp_Stream2Mem_fu_58_m_axi_out_V_AWQOS;
    sc_signal< sc_lv<4> > grp_Stream2Mem_fu_58_m_axi_out_V_AWREGION;
    sc_signal< sc_lv<1> > grp_Stream2Mem_fu_58_m_axi_out_V_AWUSER;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_m_axi_out_V_WVALID;
    sc_signal< sc_lv<64> > grp_Stream2Mem_fu_58_m_axi_out_V_WDATA;
    sc_signal< sc_lv<8> > grp_Stream2Mem_fu_58_m_axi_out_V_WSTRB;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_m_axi_out_V_WLAST;
    sc_signal< sc_lv<1> > grp_Stream2Mem_fu_58_m_axi_out_V_WID;
    sc_signal< sc_lv<1> > grp_Stream2Mem_fu_58_m_axi_out_V_WUSER;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_m_axi_out_V_ARVALID;
    sc_signal< sc_lv<64> > grp_Stream2Mem_fu_58_m_axi_out_V_ARADDR;
    sc_signal< sc_lv<1> > grp_Stream2Mem_fu_58_m_axi_out_V_ARID;
    sc_signal< sc_lv<32> > grp_Stream2Mem_fu_58_m_axi_out_V_ARLEN;
    sc_signal< sc_lv<3> > grp_Stream2Mem_fu_58_m_axi_out_V_ARSIZE;
    sc_signal< sc_lv<2> > grp_Stream2Mem_fu_58_m_axi_out_V_ARBURST;
    sc_signal< sc_lv<2> > grp_Stream2Mem_fu_58_m_axi_out_V_ARLOCK;
    sc_signal< sc_lv<4> > grp_Stream2Mem_fu_58_m_axi_out_V_ARCACHE;
    sc_signal< sc_lv<3> > grp_Stream2Mem_fu_58_m_axi_out_V_ARPROT;
    sc_signal< sc_lv<4> > grp_Stream2Mem_fu_58_m_axi_out_V_ARQOS;
    sc_signal< sc_lv<4> > grp_Stream2Mem_fu_58_m_axi_out_V_ARREGION;
    sc_signal< sc_lv<1> > grp_Stream2Mem_fu_58_m_axi_out_V_ARUSER;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_m_axi_out_V_RREADY;
    sc_signal< sc_logic > grp_Stream2Mem_fu_58_m_axi_out_V_BREADY;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_ap_start;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_ap_done;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_ap_idle;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_ap_ready;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_in_V_V_read;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWVALID;
    sc_signal< sc_lv<64> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWADDR;
    sc_signal< sc_lv<1> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWID;
    sc_signal< sc_lv<32> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWLEN;
    sc_signal< sc_lv<3> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWSIZE;
    sc_signal< sc_lv<2> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWBURST;
    sc_signal< sc_lv<2> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWLOCK;
    sc_signal< sc_lv<4> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWCACHE;
    sc_signal< sc_lv<3> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWPROT;
    sc_signal< sc_lv<4> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWQOS;
    sc_signal< sc_lv<4> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWREGION;
    sc_signal< sc_lv<1> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_AWUSER;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_WVALID;
    sc_signal< sc_lv<64> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_WDATA;
    sc_signal< sc_lv<8> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_WSTRB;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_WLAST;
    sc_signal< sc_lv<1> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_WID;
    sc_signal< sc_lv<1> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_WUSER;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARVALID;
    sc_signal< sc_lv<64> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARADDR;
    sc_signal< sc_lv<1> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARID;
    sc_signal< sc_lv<32> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARLEN;
    sc_signal< sc_lv<3> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARSIZE;
    sc_signal< sc_lv<2> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARBURST;
    sc_signal< sc_lv<2> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARLOCK;
    sc_signal< sc_lv<4> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARCACHE;
    sc_signal< sc_lv<3> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARPROT;
    sc_signal< sc_lv<4> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARQOS;
    sc_signal< sc_lv<4> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARREGION;
    sc_signal< sc_lv<1> > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_ARUSER;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_RREADY;
    sc_signal< sc_logic > grp_Stream2Mem_64u_8u_s_fu_68_m_axi_out_V_BREADY;
    sc_signal< sc_logic > ap_reg_grp_Stream2Mem_fu_58_ap_start;
    sc_signal< sc_lv<1> > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_reg_grp_Stream2Mem_64u_8u_s_fu_68_ap_start;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    sc_signal< sc_lv<1> > ap_NS_fsm_state3;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > rep_fu_42;
    sc_signal< sc_lv<32> > rep_2_fu_107_p2;
    sc_signal< sc_lv<32> > rep_1_fu_117_p2;
    sc_signal< sc_lv<32> > repsLeft_fu_92_p2;
    sc_signal< sc_lv<4> > tmp_fu_97_p1;
    sc_signal< bool > ap_condition_388;
    sc_signal< bool > ap_condition_400;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_fsm_state1;
    static const sc_lv<11> ap_ST_fsm_state2;
    static const sc_lv<11> ap_ST_fsm_state3;
    static const sc_lv<11> ap_ST_fsm_state4;
    static const sc_lv<11> ap_ST_fsm_state5;
    static const sc_lv<11> ap_ST_fsm_state6;
    static const sc_lv<11> ap_ST_fsm_state7;
    static const sc_lv<11> ap_ST_fsm_state8;
    static const sc_lv<11> ap_ST_fsm_state9;
    static const sc_lv<11> ap_ST_fsm_state10;
    static const sc_lv<11> ap_ST_fsm_state11;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_10;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const3();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_NS_fsm_state3();
    void thread_ap_condition_148();
    void thread_ap_condition_388();
    void thread_ap_condition_400();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_Stream2Mem_64u_8u_s_fu_68_ap_start();
    void thread_grp_Stream2Mem_fu_58_ap_start();
    void thread_in_V_blk_n_AW();
    void thread_in_V_blk_n_B();
    void thread_in_V_blk_n_W();
    void thread_m_axi_in_V_ARADDR();
    void thread_m_axi_in_V_ARBURST();
    void thread_m_axi_in_V_ARCACHE();
    void thread_m_axi_in_V_ARID();
    void thread_m_axi_in_V_ARLEN();
    void thread_m_axi_in_V_ARLOCK();
    void thread_m_axi_in_V_ARPROT();
    void thread_m_axi_in_V_ARQOS();
    void thread_m_axi_in_V_ARREGION();
    void thread_m_axi_in_V_ARSIZE();
    void thread_m_axi_in_V_ARUSER();
    void thread_m_axi_in_V_ARVALID();
    void thread_m_axi_in_V_AWADDR();
    void thread_m_axi_in_V_AWBURST();
    void thread_m_axi_in_V_AWCACHE();
    void thread_m_axi_in_V_AWID();
    void thread_m_axi_in_V_AWLEN();
    void thread_m_axi_in_V_AWLOCK();
    void thread_m_axi_in_V_AWPROT();
    void thread_m_axi_in_V_AWQOS();
    void thread_m_axi_in_V_AWREGION();
    void thread_m_axi_in_V_AWSIZE();
    void thread_m_axi_in_V_AWUSER();
    void thread_m_axi_in_V_AWVALID();
    void thread_m_axi_in_V_BREADY();
    void thread_m_axi_in_V_RREADY();
    void thread_m_axi_in_V_WDATA();
    void thread_m_axi_in_V_WID();
    void thread_m_axi_in_V_WLAST();
    void thread_m_axi_in_V_WSTRB();
    void thread_m_axi_in_V_WUSER();
    void thread_m_axi_in_V_WVALID();
    void thread_memOutStrm_V_V_blk_n();
    void thread_memOutStrm_V_V_read();
    void thread_numReps_channel22_blk_n();
    void thread_numReps_channel22_read();
    void thread_out_V3_blk_n();
    void thread_out_V3_read();
    void thread_rep_1_fu_117_p2();
    void thread_rep_2_fu_107_p2();
    void thread_repsLeft_fu_92_p2();
    void thread_tmp_1_i_i_i_fu_101_p2();
    void thread_tmp_fu_97_p1();
    void thread_tmp_i_i_i_fu_87_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
