# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.3
# Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/mnt/applications/Xilinx/16.3/Vivado_HLS/2016.3/../../Vivado/2016.3/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z020clg400-1 ../xilinx_com_hls_BlackBoxJam_1_0.zip
