# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/procsys_BlackBoxJam_0_0.xci
# IP: The module: 'procsys_BlackBoxJam_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/constraints/BlackBoxJam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'procsys_BlackBoxJam_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/procsys_BlackBoxJam_0_0.xci
# IP: The module: 'procsys_BlackBoxJam_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jf2715/BNN-PYNQ/bnn/src/network/output/vivado/lfcW1A1-pynqZ1-Z2/lfcW1A1-pynqZ1-Z2.srcs/sources_1/bd/procsys/ip/procsys_BlackBoxJam_0_0/constraints/BlackBoxJam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'procsys_BlackBoxJam_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
